// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMbLYRXgochTMaWASr1i4fvk7i1zhC2Vs',
    appId: '1:319340216446:web:304f34e1fe71961390982f',
    messagingSenderId: '319340216446',
    projectId: 'arthub-d3e9c',
    authDomain: 'arthub-d3e9c.firebaseapp.com',
    databaseURL: 'https://arthub-d3e9c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'arthub-d3e9c.firebasestorage.app',
    measurementId: 'G-JGCBV4SHKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0ZgNd0ngfM1PIEurUBKHId0vizNBjb0M',
    appId: '1:319340216446:android:dbf01f6cc0fb802c90982f',
    messagingSenderId: '319340216446',
    projectId: 'arthub-d3e9c',
    databaseURL: 'https://arthub-d3e9c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'arthub-d3e9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAdsLmBptKA5bG3dsLV6XEHC64x6Ki3Bs',
    appId: '1:319340216446:ios:6f14e3f581799ac190982f',
    messagingSenderId: '319340216446',
    projectId: 'arthub-d3e9c',
    databaseURL: 'https://arthub-d3e9c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'arthub-d3e9c.firebasestorage.app',
    androidClientId: '319340216446-jboptq04mvdpoikq7snr1k5ksui86sgn.apps.googleusercontent.com',
    iosClientId: '319340216446-43e2vrbsu99ola35c7n0ef7fkuksh7fa.apps.googleusercontent.com',
    iosBundleId: 'com.example.arthubFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAdsLmBptKA5bG3dsLV6XEHC64x6Ki3Bs',
    appId: '1:319340216446:ios:6f14e3f581799ac190982f',
    messagingSenderId: '319340216446',
    projectId: 'arthub-d3e9c',
    databaseURL: 'https://arthub-d3e9c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'arthub-d3e9c.firebasestorage.app',
    androidClientId: '319340216446-jboptq04mvdpoikq7snr1k5ksui86sgn.apps.googleusercontent.com',
    iosClientId: '319340216446-43e2vrbsu99ola35c7n0ef7fkuksh7fa.apps.googleusercontent.com',
    iosBundleId: 'com.example.arthubFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMbLYRXgochTMaWASr1i4fvk7i1zhC2Vs',
    appId: '1:319340216446:web:1712bfd1f706350890982f',
    messagingSenderId: '319340216446',
    projectId: 'arthub-d3e9c',
    authDomain: 'arthub-d3e9c.firebaseapp.com',
    databaseURL: 'https://arthub-d3e9c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'arthub-d3e9c.firebasestorage.app',
    measurementId: 'G-CQ2V97KLWW',
  );
}
